import streamlit as st
import requests

# 1. Page Configuration & Kaze AI Theme Styling
st.set_page_config(page_title="Kaze AI Assistant", page_icon="✨", layout="centered")

st.markdown("<h1 style='text-align: center; color: #00e5ff;'>✨ KAZE AI</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #8ab4f8;'>System online. Powered by Unblocked HuggingFace Engine.</p>", unsafe_allow_html=True)

# 2. Permanent Memory/Chat History Storage
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display all previous messages in clean chat bubbles on screen
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# 3. User Interaction - The Chat Input Box
if user_prompt := st.chat_input("Ask Kaze AI anything..."):
    
    # Immediately show what the user typed in a user bubble
    with st.chat_message("user"):
        st.write(user_prompt)
    st.session_state.messages.append({"role": "user", "content": user_prompt})

    # Show a sleek thinking animation while generating response
    with st.chat_message("assistant"):
        with st.spinner("Kaze AI is thinking... 🧠"):
            try:
                # ⚙️ HUGGING FACE FREE UNBLOCKED ENGINE ROUTING
                # This safely posts your prompt to a massive, stable public model cluster
                api_url = "https://huggingface.co"
                
                payload = {
                    "inputs": f"<|system|>\nYou are Kaze AI, a highly advanced, ultra-intelligent, helpful, and friendly AI assistant.</s>\n<|user|>\n{user_prompt}</s>\n<|assistant|>\n",
                    "parameters": {"max_new_tokens": 250, "temperature": 0.7}
                }
                
                response = requests.post(api_url, json=payload)
                data = response.json()
                
                # Extract out the pure text answer generated by the model
                if isinstance(data, list) and len(data) > 0 and "generated_text" in data[0]:
                    full_text = data[0]["generated_text"]
                    # Clean out the formatting tags so only the real answer shows
                    kaze_reply = full_text.split("<|assistant|>\n")[-1].strip()
                else:
                    kaze_reply = "My neural nodes are waking up! Please try sending your message one more time."
                
                st.write(kaze_reply)
                
                # Save Kaze AI's reply to the chat memory
                st.session_state.messages.append({"role": "assistant", "content": kaze_reply})
                
            except Exception as e:
                st.error(f"Engine connection issue: {e}")
